Added ncurses, essentials and corefs.
raven-os/nbuild-manifests pull request #2
Opened 2018-12-19 02:06 UTC by Arignir

The big part is ncurses, essentials and corefs are micro-packages.

Also, this PR uses code added by https://github.com/raven-os/nbuild/pull/15, so it's probably not a good idea to merge this before it is merged.

2018-12-21 20:57 UTC, melis-m requested changes

2018-12-21 20:57 UTC, melis-m commented on raven-os/essentials/0.1.0/manifest.py
> +    open(f'{package.install_dir}/.essentials.nestkeep', 'w+')
Garbage collection will probably close this at the end of the function, however you should still close it manually.
Also, why `w+` ? It's like `w` but with read permission as well, `w` already creates the file if it doesn't exist.
```suggestion
    open(f'{package.install_dir}/.essentials.nestkeep', 'w').close()
```
(Didn't notice it before but it also applies to `nbuild/stdenv/install.py:14` from the `nbuild` repository)

2018-12-21 20:57 UTC, melis-m commented on raven-os/essentials/0.1.0/manifest.py
> +    open(f'{package.install_dir}/.essentials-dev.nestkeep', 'w+')
Same as above
```suggestion
    open(f'{package.install_dir}/.essentials-dev.nestkeep', 'w').close()
```

2018-12-21 20:57 UTC, melis-m commented on raven-os/corefs/0.1.0/manifest.py
> +    id=f'stable::raven-os/corefs#0.1.0',
Unnecessary `f` in front of the string (might have been to put the version as a variable that would have been defined above?)

2018-12-21 20:57 UTC, melis-m commented on raven-os/essentials/0.1.0/manifest.py
> +    id=f'stable::raven-os/essentials#0.1.0',
Unnecessary `f` in front of string, like `corefs`.

2018-12-22 01:23 UTC, Arignir commented on raven-os/essentials/0.1.0/manifest.py
> +    open(f'{package.install_dir}/.essentials.nestkeep', 'w+')
Nice catch

2018-12-22 01:23 UTC, Arignir commented on raven-os/corefs/0.1.0/manifest.py
> +    id=f'stable::raven-os/corefs#0.1.0',
Yeah, missed copy paste.

2018-12-22 01:24 UTC, Arignir commented on raven-os/essentials/0.1.0/manifest.py
> +    id=f'stable::raven-os/essentials#0.1.0',
Same here.

2018-12-22 01:24 UTC, Arignir commented
I'll do the small fixes tomorrow, thanks!

2019-06-22 18:07 UTC, closed without merging